version: '3.7'

services:

  web:
    build:
      dockerfile: dockerfiles/web.Dockerfile
      context: .
    expose:
      - 80
    environment:
      - PORT=80
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`web.localhost`)
      - traefik.http.routers.whoami.entrypoints=web

  traefik:
    image: traefik:v2.3.3
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
